apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: substreams-tier2-scaler
spec:
  scaleTargetRef:
    name: substreams-tier2
  pollingInterval:  5                                       # Optional. Default: 30 seconds
  cooldownPeriod:   30                                      # Optional. Default: 300 seconds
  minReplicaCount:  1                                       # Optional. Default: 0
  maxReplicaCount:  10
  triggers:
  - type: prometheus
    metadata:
      serverAddress:
      metricName:
      threshold: 
      query: 