apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: substreams-tier2-scaler
spec:
  scaleTargetRef:
    name: substreams-tier2
  pollingInterval:  5                                       # Optional. Default: 30 seconds
  cooldownPeriod:   30                                      # Optional. Default: 300 seconds
  idleReplicaCount: 0
  minReplicaCount:  1                                       # Optional. Default: 0
  maxReplicaCount:  10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.monitoring:9090
      metricName: substreams_block_process_start_counter
      threshold: "0.03"
      query: rate(container_cpu_usage_seconds_total{container="substreams-tier1"}[1m])