apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
spec:
  type: NodePort
  ports:
    - port: 8333
      nodePort: 30000
      targetPort: s3
      protocol: TCP
  selector:
    app: seaweedfs
