apiVersion: v1
kind: Service
metadata:
  name: relayer
spec:
  type: ClusterIP
  selector:
    app: relayer
  ports:
    - name: grpc
      port: 13011
      protocol: TCP
      targetPort: grpc
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: prom
