---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-release
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: keda-repo
  interval: 5m
  values:
    image:
      keda:
        repository: ghcr.io/kedacore/keda
        tag: main

    nimbus:
      executionClientUrl: http://eth-consensus:8547
      jwt:
        existingSecret:
          name: jwt
          key: jwt.hex

      p2pNodePort:  
        enabled: true
        port: 31000
      
      trustedNodeSync:
        enabled: true
        trustedNodeUrl: https://beaconstate.info

    prometheus:
      operator:
        enabled: true

    grafana:
      dashboards: true
