---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 6h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: cilium
      version: "1.14.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
  targetNamespace: kube-system
  install:
    createNamespace: true
  values:
    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enableOpenMetrics: true
        enabled: "{dns,drop,tcp,flow,port-distribution,icmp,httpV2}"
