---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: keda
  interval: 5m
  values:
    image:
      keda:
        repository: ghcr.io/kedacore/keda
        tag: main
    prometheus:
      operator:
        enabled: true
    grafana:
      dashboards: true
