apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave.yaml                    # Flux dashboard
  - traefik.yaml                  # Ingress controller
  - prometheus.yaml               # Metrics
  - openebs.yaml                  # Dynamic storage
  - keda.yaml                     # Horizontal autoscaling

# Not able to patch resources grouped by kind
# patchesStrategicMerge:
# - |-
#   apiVersion: source.toolkit.fluxcd.io/v1beta2
#   kind: HelmRepository
#   metadata:
#     name: prometheus
#     namespace: flux-system
#   spec:
#     interval: 6h

# - |-
#   apiVersion: helm.toolkit.fluxcd.io/v2beta1
#   kind: HelmRelease
#   metadata:
#     name: prometheus
#     namespace: flux-system
#     annotations:
#       helm.fluxcd.io/uninstall: "true"
#   spec:
#     createNamespace: true
#     interval: 6h
#     chart:
#       spec:
#         interval: 6h
