apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave.yaml                    # Flux dashboard
  # - traefik.yaml                  # Ingress controller
  - prometheus.yaml               # Metrics
  - loki.yaml                     # Logs
  - tempo.yaml                    # Traces
  - odigos.yaml                   # Instrumentation
  # - otel.yaml                     # OpenTelemetry
  # - openebs.yaml                  # Dynamic storage
  # - keda.yaml                     # Horizontal autoscaling
