apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave.yaml                    # Flux dashboard
  - traefik.yaml                  # Ingress controller
  - prometheus.yaml               # Metrics
  - openebs.yaml                  # Dynamic storage
  - keda.yaml                     # Horizontal autoscaling

patches:
- target:
    kind: HelmRepository
  patch: |
    - op: add
      metadata:
        namespace: flux-system
      spec:
        interval: 6h

- target:
    kind: HelmRelease
  patch: |
    - op: add
      metadata:
        namespace: flux-system
        annotations:
          helm.fluxcd.io/uninstall: true
      spec:
        createNamespace: true
        interval: 6h
        chart:
          spec:
            interval: 6h