apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: flux-system
resources:
  - namespaces.yaml               # Namespaces
  - weave.yaml                    # Flux dashboard
  - prometheus.yaml               # Metrics
  - traefik.yaml                  # Ingress controller
  - openebs.yaml                  # Dynamic storage
  - keda.yaml                     # Horizontal autoscaling