apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave.yaml                    # Flux dashboard
  - traefik.yaml                  # Ingress controller
  - prometheus.yaml               # Metrics
  - openebs.yaml                  # Dynamic storage
  - keda.yaml                     # Horizontal autoscaling

patches:
- target:
    kind: HelmRepository
  patch: |
    - op: add
      path: /metadata/namespace
      value: flux-system
    - op: add
      path: /spec/interval
      value: 6h

- target:
    kind: HelmRelease
  patch: |
    - op: add
      path: /metadata/namespace
      value: flux-system
    - op: add
      path: /metadata/annotations
      value: helm.fluxcd.io/uninstall: true
    - op: add
      path: /spec/createNamespace
      value: true
    - op: add
      path: /spec/interval
      value: 6h
    - op: add
      path: /spec/chart/spec/interval
      value: 6h
