apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - weave.yaml                    # Flux dashboard
  - traefik.yaml                  # Ingress controller
  - prometheus.yaml               # Metrics
  - openebs.yaml                  # Dynamic storage
  - keda.yaml                     # Horizontal autoscaling
