---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 60m
  url: https://openebs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: openebs
      version: "3.9.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 12h