---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
spec:
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "51.9.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 12h
  targetNamespace: monitoring
  values: 
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        path: /prometheus
        pathType: Prefix
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        path: /grafana
        pathType: Prefix