---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "51.9.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 12h
    values: 
      namespaceOverride: prometheus