---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 6h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "51.9.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus
  targetNamespace: monitoring
  install:
    createNamespace: true

  values: 
    prometheus:
      ingress:
        enabled: true
        # ingressClassName: traefik
        ingressClassName: nginx
        path: /prometheus
      prometheusSpec:
        enableFeatures:
          - remote-write-receiver
    grafana:
      ingress:
        enabled: true
        # ingressClassName: traefik
        ingressClassName: nginx
        path: /grafana
      # Data sources to have traces and logs
      datasources:
        enabled: true
        defaultDatasourceEnabled: true
        isDefaultDatasource: true
        uid: prometheus
        url: http://monitoring-prometheus-kube-prometheus:9090
      additionalDataSources:
        - name: Tempo
          type: tempo
          access: browser
          uid: tempo
          isDefault: false
          editable: true
          service_graphs:
            enabled: true
          url: http://monitoring-tempo.monitoring:3100
        - name: Loki
          type: loki
          access: browser
          uid: loki
          isDefault: false
          editable: true
          url: http://monitoring-loki.monitoring:3100
          jsonData:
          derivedFields:
            - datasourceName: Tempo
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
              datasourceUid: tempo