---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
spec:
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 12h
  targetNamespace: traefik
  values:
    service:
      type: NodePort