---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nimbus-release
  namespace: sf-ethereum
spec:
  chart:
    spec:
      chart: nimbus
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: nimbus-repo
  interval: 5m
  values:
    - ./values.yaml
