apiVersion: v1
kind: Service
metadata:
  name: firehose
spec:
  type: ClusterIP
  selector:
    app: firehose
  ports:
    - name: grpc
      port: 13042
      protocol: TCP
      targetPort: grpc
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: 9102

