---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nimbus
  namespace: flux-system
spec:
  interval: 60m
  url: https://graphops.github.io/launchpad-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nimbus
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: nimbus
      version: 0.5.2
      sourceRef:
        kind: HelmRepository
        name: nimbus
  targetNamespace: sf-ethereum
  values:
    image:
      tag: multiarch-v23.9.0

    nimbus:
      executionClientUrl: http://eth-consensus:8547
      jwt:
        existingSecret:
          name: jwt
          key: jwt.hex

      p2pNodePort:  
        enabled: true
        port: 31000
      
      trustedNodeSync:
        enabled: true
        trustedNodeUrl: https://beaconstate.info

      volumeClaimSpec:
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 300Gi

    prometheus:
      serviceMonitors:
        enabled: true

    grafana:
      dashboards: true
