---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sf-ethereum
resources:
  - setup
  - reader-node
  - merger
  - relayer
  - indexer
  - firehose
  - nimbus
  - seaweedfs
  # - substreams-tier1
  # - substreams-tier1

images:
  - name: fireeth
    newName: ghcr.io/streamingfast/firehose-ethereum
    newTag: v1.4.14-geth-v1.12.2-fh2.3-1
