---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sf-ethereum
resources:
  - setup
  - reader-node
  - merger
  - relayer
  - indexer
  - firehose
  - nimbus
  - seaweedfs

images:
  - name: fireeth
    newName: ghcr.io/streamingfast/firehose-ethereum
    newTag: v1.3.8-geth-v1.11.5-fh2.2
