---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sf-ethereum
resources:
  - setup
  - reader-node
  - merger
  - relayer
  - indexer
  - firehose
  - nimbus
  - seaweedfs
