apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  type: ClusterIP
  selector:
    app: indexer
  ports:
    - name: grpc-healthz
      port: 13043
      protocol: TCP
      targetPort: grpc-healthz
