---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fireeth
  namespace: flux-system
spec:
  dependsOn:
    - name: openebs-storage
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app/fireeth_k8s
  prune: true
  wait: true
  timeout: 5m0s
